### ISSUE TITLE
How to use this as an asset in containerised sensu-backend?

### ISSUE THREAD

**Issue by rohan-1202** [betorvs/sensu-opsgenie-handler#1]
Hello,
My issue how can we use this handler as an asset inside a sensu-backend which is deployed in docker? So in general, I have installed all the asset using `sensuctl create` command from the host which requires an asset definition for it to be fetched. Can we have something similar for this handler as well? Or if is already there then can I get some docs which refer to that?

**Comment by betorvs** [comment]
Hi @rohan-1202 , Thanks for asking. 
I don't use asset yet, but I created a new release 0.0.4 with sensu bonsai configured. And now I have checksum there. Check it: https://bonsai.sensu.io/assets/betorvs/sensu-opsgenie-handler
```
linux amd64
https://assets.bonsai.sensu.io/fba8c41f2b5bc817f8fb201144627042a3e31ee3/sensu-opsgenie-handler_0.0.4_linux_amd64.tar.gz
SHA: 5eda4b31371fae83860604dedbf8527d0d6919bfae8e4f5b33f71bd314f6d706ef80356b14f11d7d2f86923df722338a3d11b84fa1e35323959120b46b738487
Last Modified: 2019-08-26
```
Please test if these command works for you: 
```
sensuctl asset create sensu-opsgenie-handler --url "https://assets.bonsai.sensu.io/fba8c41f2b5bc817f8fb201144627042a3e31ee3/sensu-opsgenie-handler_0.0.4_linux_amd64.tar.gz" --sha512 "5eda4b31371fae83860604dedbf8527d0d6919bfae8e4f5b33f71bd314f6d706ef80356b14f11d7d2f86923df722338a3d11b84fa1e35323959120b46b738487"
```

**Comment by FredrikWendt** [comment]
For anyone stumbling upon this, this works just fine for me: the sensu-backend process downloads the asset from the URL specified in the asset definition. (It's unpacked in the containers filesystem under `/var/cache/sensu/sensu-backend/__SHA512__/`.)
