### ISSUE TITLE
Allow changing [Sensu] to [Sensu Go] (or other arbitrary text string)

### ISSUE THREAD

**Issue by mwtzzz-zz** [betorvs/sensu-opsgenie-handler#11]
Alerts from both Sensu Enterprise and Sensu Go show up as [Sensu] in Opsgenie. We'd like a way to distinguish them, it would be ideal if we could have [Sensu Go] for alerts coming from the new platform.

**Comment by nixwiz** [comment]
If I'm not mistaken that is part of your Integration, not the handler.  See the screenshot below.
<img width="437" alt="Screen Shot 2020-04-30 at 12 44 41 PM" src="https://user-images.githubusercontent.com/5530473/80752583-8fe9e800-8ae0-11ea-8535-64f5b613505c.png">


The only way to change that would be to use a separate integration definition.

**Comment by mwtzzz-zz** [comment]
That's what I was thinking, but I wanted to make sure.
Thanks for the info.

- Michael
