### ISSUE TITLE
Passing check output details into the message line and description fields

### ISSUE THREAD

**Issue by mwtzzz-zz** [betorvs/sensu-opsgenie-handler#12]
In sensu enterprise, the first portion of check output gets appended to the opsgenie Message line, with the full output going to the Description.

We'd like to ask the same behavior (or at least the option to include these details) in Sensu Go. 

Thank you!

**Comment by betorvs** [comment]
Hi @mwtzzz can you share a screenshot about it? I never used sensu enterprise and I don't understand what you need. 
The latest version, 1.0.0-beta have some details from entity like arch and operation system. Do you want to have a extra details called description with full check output?

**Comment by mwtzzz-zz** [comment]
@betorvs I believe sensu support is already taking care of this. They've added a flag to include check.output in the Message field and a flag to toggle whether stuff gets appended to the Notes field or not. They're currently working on fixing the flag to include check output in the Description field.

**Comment by betorvs** [comment]
Thanks @mwtzzz Closing this issue.
