### ISSUE TITLE
Plugin does not work for region Europe

### ISSUE THREAD

**Issue by koenverwimp** [betorvs/sensu-opsgenie-handler#3]
Hi Roberto,

My opsgenie account is located in the European Service Region and apparently your plug-in does only work for US region. (https://docs.opsgenie.com/v1.0/docs/european-service-region)

Is it possible to make the region configurable?

Kind regards,
Koen

**Comment by betorvs** [comment]
Hi @koenverwimp, 

Yes, it is. 

I did some changes and test it. Looks ok. 

Could you test it for me? Its need a new environment variable `OPSGENIE_APIURL` with the new url "https://api.eu.opsgenie.com".

I keep these variable as a string to use it for testing purpose. 

Thanks for using it.

**Comment by koenverwimp** [comment]
I did a quick test and it seems to work! 
THANK YOU VERY MUCH :-)

**Comment by FredrikWendt** [comment]
And for those not using the EU version, the `OPSGENIE_APIURL` needs to be `https://api.opsgenie.com/`, which happens to be the default if not configured.
