### ISSUE TITLE
trim additional ending slash in --url argument

### ISSUE THREAD

**Issue by FredrikWendt** [betorvs/sensu-opsgenie-handler#6]
OpsGenie's API is slash-sensitive. 

Works:
`cat event.json | ./sensu-opsgenie-handler --auth 'abcdef....' --team '.....' --url 'https://api.eu.opsgenie.com'`

Doesn't work:
`cat event.json | ./sensu-opsgenie-handler --auth 'abcdef....' --team '.....' --url 'https://api.eu.opsgenie.com/'`

The error I got when using a `--url` argument that ended with a slash, was this:

`Client error occurred; Response Code: 404, Response Body: {"message":"No handler found","took":0.002,"requestId":"0fe4ca23-1f6e-4449-82fc-11111111111111"}`

**Comment by betorvs** [comment]
Please, could you test release 0.0.7 @FredrikWendt . I did some tests here and looks ok now.

**Comment by FredrikWendt** [comment]
Tried 0.0.7 (linux-amd64) and --url ending with a slash: worked fine, an alert was created in OpsGenie (rather than HTTP 404).
