### ISSUE TITLE
payload info

### ISSUE THREAD

**Issue by hprins** [betorvs/sensu-opsgenie-handler#8]
Greetings, 

Is there a way keep receiving the payload info that Sensu classic provides?  Our Opsgenie alerts depend on name, ip, subscriptions, team, etc.  The Go version does not provide this info by default.  Is there something I need to do?  See attached files for more information.  Thanks.

![classic_payload_info](https://user-images.githubusercontent.com/26799700/72897505-1e83e780-3cf0-11ea-9589-37481be02ef3.JPG)
![go_payload_info](https://user-images.githubusercontent.com/26799700/72897507-1e83e780-3cf0-11ea-9b05-c35b7860ff63.JPG)
![go_alert_log_info](https://user-images.githubusercontent.com/26799700/72897508-1e83e780-3cf0-11ea-9e71-fef4ae7a7fb4.JPG)

**Comment by betorvs** [comment]
Hi @hprins , please test this new version 0.0.9: https://bonsai.sensu.io/assets/betorvs/sensu-opsgenie-handler. 
And thanks for using opsgenie handler.

**Comment by hprins** [comment]
@betorvs this works well.  Thanks for assisting.
